import { Post } from "@/types";

export const posts: Post[] = [
  {
    image: "/images/sales.jpg",
    name: "Sales and tele-sales Rep",
    features: [
      "Bachelor Degree",
      "Male&Female",
      "Mid Level",
      "Experience (1-3) Yrs",
      "Age (23-27)",
    ],
    budget: "Confidential",

    url: "https://docs.google.com/forms/d/e/1FAIpQLSfJ711QkFqnltmx3GtckQjfApBJdNl_9wJ9IlTqMyRYBCraaw/viewform?usp=sf_link",
    location: "Nasr City, Cairo",
    jobTime: "Full Time | On Site",
  },
  {
    image: "/images/sales team leader.jpg",
    name: "Sales Team Leader",
    features: [
      "Bachelor Degree",
      "Male&Female",
      "Mid Level",
      "Experience (3-5) Yrs",
      "Age (23-28)",
    ],
    budget: "Confidential",
    url: "https://docs.google.com/forms/d/e/1FAIpQLSexosNHWxyMmXThzHLCSQ_FgDEJW2fYYTD_VVUIs_CDcKMswg/viewform?usp=header",
    location: "Nasr City, Cairo",
    jobTime: "Full Time | On Site",
  },
  {
    image: "/images/key account.jpg",
    name: "Key Account Manager",
    features: [
      "Bachelor Degree",
      "Male&Female",
      "Mid Level",
      "Experience (3-5) Yrs",
      "Age (25-29)",
    ],
    budget: "Confidential",
    url: "https://docs.google.com/forms/d/e/1FAIpQLSdhKexMn2xJsdmUX0v15igbbF9NZRVpMfe2VmZ3oRypewy-sA/viewform?usp=header",
    location: "Nasr City, Cairo",
    jobTime: "Full Time | On Site",
  },
  {
    image: "/images/social media.jpg",
    name: "Social Media Specialist",
    features: [
      "Bachelor Degree",
      "Male&Female",
      "Mid Level",
      "Experience (2-4) Yrs",
      "Age (23-28)",
    ],
    budget: "Confidential",
    url: "https://docs.google.com/forms/d/e/1FAIpQLSclxPQVV1XfiRUzu0YcxlaPfVgBSL7-TbPYAWnE1bHpea2dCg/viewform?usp=dialog",
    location: "Nasr City, Cairo",
    jobTime: "Full Time | On Site",
  },
  {
    image: "/images/business developer.jpg",
    name: "Business Development Executive",
    features: [
      "Bachelor Degree",
      "Male&Female",
      "Mid Level",
      "Experience (3-5) Yrs",
      "Age (27-32)",
    ],
    budget: "Confidential",
    url: "https://docs.google.com/forms/d/e/1FAIpQLSdU6w12RiNxETzjYXswmSRs7CkrM28anU3w5wdHsPFcfIMnvA/viewform?usp=header",
    location: "Nasr City, Cairo",
    jobTime: "Full Time | On Site",
  },
  {
    image: "/images/hr.jpg",
    name: "HR Recruiter",
    features: [
      "Bachelor Degree",
      "Male&Female",
      "Mid Level",
      "Experience (3-5) Yrs",
      "Age (26-32)",
    ],
    budget: "Confidential",
    url: "https://docs.google.com/forms/d/e/1FAIpQLSfPMfe1BlexpB1OeXKqsCq6azVp58BcvL4_EF8DDj2X7QaIEQ/viewform?usp=header",
    location: "Nasr City, Cairo",
    jobTime: "Full Time | On Site",
  },
];
