import { Post } from "@/types";

export const posts: Post[] = [
  {
    image: "/images/poter.jpg",
    name: "Sales Representative",
    features: [
      "Bachelor Degree",
      "Male&Female",
      "Mid Level",
      "Experience (3-5) Yrs",
      "Age (23-28)",
    ],
    budget: "Confidential",

    url: "https://medicova.com",
    location: "Nasr City, Cairo",
    jobTime: "Full Time | On Site",
  },
  {
    image: "/images/image1.jpeg",
    name: "Consultant Cardiology",
    features: [
      "Bachelor Degree",
      "Male&Female",
      "Mid Level",
      "Experience (3-5) Yrs",
      "Age (23-28)",
    ],
    budget: "Confidential",
    url: "https://medicova.com",
    location: "Nasr City, Cairo",
    jobTime: "Full Time | On Site",
  },
  {
    image: "/images/image1.jpeg",
    name: "Consultant Cardiology",
    features: [
      "Bachelor Degree",
      "Male&Female",
      "Mid Level",
      "Experience (3-5) Yrs",
      "Age (23-28)",
    ],
    budget: "Confidential",
    url: "https://medicova.com",
    location: "Nasr City, Cairo",
    jobTime: "Full Time | On Site",
  },
  {
    image: "/images/image1.jpeg",
    name: "Consultant Cardiology",
    features: [
      "Bachelor Degree",
      "Male&Female",
      "Mid Level",
      "Experience (3-5) Yrs",
      "Age (23-28)",
    ],
    budget: "Confidential",
    url: "https://medicova.com",
    location: "Nasr City, Cairo",
    jobTime: "Full Time | On Site",
  },
  {
    image: "/images/image1.jpeg",
    name: "Consultant Cardiology",
    features: [
      "Bachelor Degree",
      "Male&Female",
      "Mid Level",
      "Experience (3-5) Yrs",
      "Age (23-28)",
    ],
    budget: "Confidential",
    url: "https://medicova.com",
    location: "Nasr City, Cairo",
    jobTime: "Full Time | On Site",
  },
  {
    image: "/images/image1.jpeg",
    name: "Consultant Cardiology",
    features: [
      "Bachelor Degree",
      "Male&Female",
      "Mid Level",
      "Experience (3-5) Yrs",
      "Age (23-28)",
    ],
    budget: "Confidential",
    url: "https://medicova.com",
    location: "Nasr City, Cairo",
    jobTime: "Full Time | On Site",
  },
];
