import { Post } from "@/types";

export const posts: Post[] = [
  {
    image: "/images/poter.jpg",
    name: "Sales and tele-sales Rep",
    features: [
      "Bachelor Degree",
      "Male&Female",
      "Mid Level",
      "Experience (1-3) Yrs",
      "Age (23-27)",
    ],
    budget: "Confidential",

    url: "https://docs.google.com/forms/d/e/1FAIpQLSfJ711QkFqnltmx3GtckQjfApBJdNl_9wJ9IlTqMyRYBCraaw/viewform?usp=sf_link",
    location: "Nasr City, Cairo",
    jobTime: "Full Time | On Site",
  },
  {
    image: "/images/image1.jpeg",
    name: "Consultant Cardiology",
    features: [
      "Bachelor Degree",
      "Male&Female",
      "Mid Level",
      "Experience (3-5) Yrs",
      "Age (23-28)",
    ],
    budget: "Confidential",
    url: "https://medicova.com",
    location: "Nasr City, Cairo",
    jobTime: "Full Time | On Site",
  },
  {
    image: "/images/image1.jpeg",
    name: "Consultant Cardiology",
    features: [
      "Bachelor Degree",
      "Male&Female",
      "Mid Level",
      "Experience (3-5) Yrs",
      "Age (23-28)",
    ],
    budget: "Confidential",
    url: "https://medicova.com",
    location: "Nasr City, Cairo",
    jobTime: "Full Time | On Site",
  },
  {
    image: "/images/image1.jpeg",
    name: "Consultant Cardiology",
    features: [
      "Bachelor Degree",
      "Male&Female",
      "Mid Level",
      "Experience (3-5) Yrs",
      "Age (23-28)",
    ],
    budget: "Confidential",
    url: "https://medicova.com",
    location: "Nasr City, Cairo",
    jobTime: "Full Time | On Site",
  },
  {
    image: "/images/image1.jpeg",
    name: "Consultant Cardiology",
    features: [
      "Bachelor Degree",
      "Male&Female",
      "Mid Level",
      "Experience (3-5) Yrs",
      "Age (23-28)",
    ],
    budget: "Confidential",
    url: "https://medicova.com",
    location: "Nasr City, Cairo",
    jobTime: "Full Time | On Site",
  },
  {
    image: "/images/image1.jpeg",
    name: "Consultant Cardiology",
    features: [
      "Bachelor Degree",
      "Male&Female",
      "Mid Level",
      "Experience (3-5) Yrs",
      "Age (23-28)",
    ],
    budget: "Confidential",
    url: "https://medicova.com",
    location: "Nasr City, Cairo",
    jobTime: "Full Time | On Site",
  },
];
