export const posts = [
  {
    image: "/images/logo.png",
    date: "since 6 days",
    name: "Consultant Cardiology",
    features: [
      "Full Time",
      "Onsite",
      "Master’s Degree",
      "Cardio-vascular",
      "Male and Female",
      "Consultant",
      "Experience (3-5) Years",
      "Age (30-40)",
    ],
    budget: "20000 EGP",
    country: "Egypt",
    category: "Cardiology",
    specialty: "doctors",
    applicant: "10",
    maxApplicant: "50",
  },
  {
    image: "/images/logo.png",
    date: "since 6 days",
    name: "Consultant Cardiology",
    features: [
      "Full Time",
      "Onsite",
      "Master’s Degree",
      "Cardio-vascular",
      "Male and Female",
      "Consultant",
      "Experience (3-5) Years",
      "Age (30-40)",
    ],
    budget: "20000 EGP",
    country: "Egypt",
    category: "Cardiology",
    specialty: "doctors",
    applicant: "10",
    maxApplicant: "50",
  },
  {
    image: "/images/logo.png",
    date: "since 6 days",
    name: "Consultant Cardiology",
    features: [
      "Full Time",
      "Onsite",
      "Master’s Degree",
      "Cardio-vascular",
      "Male and Female",
      "Consultant",
      "Experience (3-5) Years",
      "Age (30-40)",
    ],
    budget: "20000 EGP",
    country: "Egypt",
    category: "Cardiology",
    specialty: "doctors",
    applicant: "10",
    maxApplicant: "50",
  },
  {
    image: "/images/logo.png",
    date: "since 6 days",
    name: "Consultant Cardiology",
    features: [
      "Full Time",
      "Onsite",
      "Master’s Degree",
      "Cardio-vascular",
      "Male and Female",
      "Consultant",
      "Experience (3-5) Years",
      "Age (30-40)",
    ],
    budget: "20000 EGP",
    country: "Egypt",
    category: "Cardiology",
    specialty: "doctors",
    applicant: "10",
    maxApplicant: "50",
  },
  {
    image: "/images/logo.png",
    date: "since 6 days",
    name: "Consultant Cardiology",
    features: [
      "Full Time",
      "Onsite",
      "Master’s Degree",
      "Cardio-vascular",
      "Male and Female",
      "Consultant",
      "Experience (3-5) Years",
      "Age (30-40)",
    ],
    budget: "20000 EGP",
    country: "Egypt",
    category: "Cardiology",
    specialty: "doctors",
    applicant: "10",
    maxApplicant: "50",
  },
  {
    image: "/images/logo.png",
    date: "since 6 days",
    name: "Consultant Cardiology",
    features: [
      "Full Time",
      "Onsite",
      "Master’s Degree",
      "Cardio-vascular",
      "Male and Female",
      "Consultant",
      "Experience (3-5) Years",
      "Age (30-40)",
    ],
    budget: "20000 EGP",
    country: "Egypt",
    category: "Cardiology",
    specialty: "doctors",
    applicant: "10",
    maxApplicant: "50",
  },
];
